spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 3000
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 3000
            #            retryer: feign.retryer.Default
feign:
  sentinel:
    default-rule: default
